name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_lab4-2
      id: test_lab4-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_lab4-2
        setup-command: ''
        command: make clean && make test_lab4-2 && make lab4-2 && ./test_files/test_lab4-2
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_lab4-3
      id: test_lab4-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_lab4-3
        setup-command: ''
        command: make clean && make test_lab4-3 && make lab4-3 && ./test_files/test_lab4-3
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_lab4-4
      id: test_lab4-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_lab4-4
        setup-command: ''
        command: make clean && make test_lab4-4 && make lab4-4 && ./test_files/test_lab4-4
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_lab4-6
      id: test_lab4-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_lab4-6
        setup-command: ''
        command: make clean && make test_lab4-6 && make lab4-6 && ./test_files/test_lab4-6
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_hw4-11
      id: test_hw4-11
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_hw4-11
        setup-command: ''
        command: make clean && make test_hw4-11 && make hw4-11 && ./test_files/test_hw4-11
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_hw4-14
      id: test_hw4-14
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_hw4-14
        setup-command: ''
        command: make clean && make test_hw4-14 && make hw4-14 && ./test_files/test_hw4-14
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: test_hw4-16
      id: test_hw4-16
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test_hw4-16
        setup-command: ''
        command: make clean && make test_hw4-16 && make hw4-16 && ./test_files/test_hw4-16
        input: ''
        expected-output: Test passed!
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_LAB4-2_RESULTS: "${{steps.test_lab4-2.outputs.result}}"
        TEST_LAB4-3_RESULTS: "${{steps.test_lab4-3.outputs.result}}"
        TEST_LAB4-4_RESULTS: "${{steps.test_lab4-4.outputs.result}}"
        TEST_LAB4-6_RESULTS: "${{steps.test_lab4-6.outputs.result}}"
        TEST_HW4-11_RESULTS: "${{steps.test_hw4-11.outputs.result}}"
        TEST_HW4-14_RESULTS: "${{steps.test_hw4-14.outputs.result}}"
        TEST_HW4-16_RESULTS: "${{steps.test_hw4-16.outputs.result}}"
      with:
        runners: test_lab4-2,test_lab4-3,test_lab4-4,test_lab4-6,test_hw4-11,test_hw4-14,test_hw4-16